# This workflow will install Python dependencies and run linters with Black and Flake8 using Python 3.11
# For more information see: https://docs.github.com/en/actions/about-github-actions

name: Run linters

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Set Python version
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Upgrade pip
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      # Install project dependencies
      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      # Run linters and formatters
      - name: Linters and formatters
        run: |
          black --check .
          flake8 .
